[package]
name = "vizij-api-core"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
hashbrown = { version = "0.14", features = ["serde"] }
