[package]
name = "animation-player"
version = "0.1.0"
authors = ["victor.paleologue"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

# Common dependencies used by both wasm and native targets
[dependencies]
lazy_static = "1.4.0"
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "0.8.2", features = ["v4", "serde"] }

# WebAssembly-specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.84"
console_error_panic_hook = { version = "0.1.7", optional = true }
serde-wasm-bindgen = "0.6.4"

# Make sure wasm-bindgen feature is only enabled for wasm32 target
[target.'cfg(target_arch = "wasm32")'.dependencies.uuid]
version = "0.8.2"
features = ["v4", "wasm-bindgen", "serde"]

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
opt-level = 3
