[workspace]
members = ["animation-player"]
resolver = "2"

[profile.release]
opt-level = "s"   # optimize for size
lto = true
codegen-units = 1
panic = "abort"   # smaller code size

[profile.release.package."*"]
opt-level = "s"
