[package]
name = "vizij-animation-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Core animation logic for Vizij (engine-agnostic)."
repository = "https://github.com/vizij/vizij-rs"

[dependencies]
serde = { workspace = true }
serde_json = "1"
