name: Continuous Integration Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./animation-player

    steps:
    - uses: actions/checkout@v3

    - name: Install WASM Pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build and test Rust crate
      run: |
        cargo build --release
        cargo test --release


    - name: Build and test Rust crate for web
      run: |
        wasm-pack build --target web
        wasm-pack test --node
        wasm-pack test --headless --firefox --chrome

    # The web assembly build is now available in the pkg directory
    # We can use it for the Web example

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ./example/npm_vite_ts/package-lock.json

    - name: Install deps and build.
      run: |
        npm i
        npm ci
        npm run build
      working-directory: ./example/npm_vite_ts

    - name: Install Playwright browsers and run tests
      run: |
        npx playwright install --with-deps
        npx playwright test
      working-directory: ./example/npm_vite_ts

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: ./example/npm_vite_ts/playwright-report/
        retention-days: 30
