name: ci
on:
  push:
  pull_request:

concurrency:
  group: rs-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: vizij-rs } }
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            vizij-rs/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('vizij-rs/**/Cargo.lock') }}
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test --all-features --all-targets

  wasm:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: vizij-rs } }
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build WASM into npm wrapper pkg/
        run: node scripts/build-wasm.mjs
      - name: Verify wrapper builds
        run: |
          cd npm/@vizij/animation-wasm
          npm ci
          npm run build
          npm pack --dry-run
