name: publish-npm
on:
  workflow_dispatch:
  push:
    tags:
      - 'npm-v*.*.*'   # e.g., npm-v0.1.3

permissions:
  contents: read
  id-token: write     # required for --provenance

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: vizij-rs } }
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build WASM into pkg/
        run: node scripts/build-wasm.mjs

      - name: Build wrapper
        run: |
          cd npm/@vizij/animation-wasm
          npm ci
          npm run build
          npm pack --dry-run

      - name: Publish @vizij/animation-wasm
        working-directory: vizij-rs/npm/@vizij/animation-wasm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: npm publish --access public --provenance
