name: publish-npm

on:
  workflow_dispatch:
  push:
    tags:
      - 'npm-pub-*'

permissions:
  contents: read
  id-token: write

jobs:
  publish_workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Enable pnpm
        run: corepack enable pnpm

      - name: Publish npm packages via Changesets
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: pnpm run publish:npm
