name: publish-all
on:
  push:
    tags:
      - 'release-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Set credentials
        run: |
          mkdir -p ~/.cargo
          cat > ~/.cargo/credentials <<EOF
          [registry]
          token = "${{ secrets.CARGO_REGISTRY_TOKEN }}"
          EOF
      - name: Publish ALL crates
        run: cargo workspaces publish --from-git --all --yes --no-verify