[package]
name = "vizij-test-fixtures"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
once_cell = "1"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

